# Generated by Django 2.2.5 on 2019-10-07 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentagenerica',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CuentaEfectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.IntegerField()),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cuenta.CuentaGenerica')),
            ],
        ),
    ]
