# Generated by Django 2.2.5 on 2019-10-07 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_auto_20191007_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentagenerica',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
