# Generated by Django 2.2.5 on 2019-11-01 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_auto_20191007_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasivos', models.PositiveIntegerField()),
                ('limite', models.PositiveIntegerField()),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cuenta.CuentaGenerica')),
            ],
        ),
    ]
