# Generated by Django 2.2.5 on 2019-11-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_tarjetacredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetacredito',
            name='saldo_inicial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
