# Generated by Django 2.2.5 on 2019-11-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_tarjetacredito_saldo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetacredito',
            name='cuota_manejo',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
