# Generated by Django 2.2.5 on 2019-11-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0008_cuentaprestamo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentaprestamo',
            old_name='numeroPeriodoPago',
            new_name='mesesPago',
        ),
    ]
