# Generated by Django 2.2.5 on 2019-11-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0010_cuentaprestamo_mesespagados'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaprestamo',
            name='pagoMensual',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
