# Generated by Django 2.2.5 on 2019-11-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0011_cuentaprestamo_pagomensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaAhorros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.PositiveIntegerField()),
                ('saldo_minimo_req', models.PositiveIntegerField()),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cuenta.CuentaGenerica')),
            ],
        ),
    ]
