# Generated by Django 2.2.5 on 2019-11-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0012_cuentaahorros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentagenerica',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='cuentas/'),
        ),
    ]
