# Generated by Django 2.2.5 on 2019-12-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0014_cuentagenerica_tipo_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaprestamo',
            name='saldoPendiente',
            field=models.PositiveIntegerField(default=1000000),
            preserve_default=False,
        ),
    ]
