# Generated by Django 2.2.5 on 2019-12-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0015_cuentaprestamo_saldopendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaprestamo',
            name='saldoPendiente',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
