# Generated by Django 2.2.5 on 2019-10-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='grupos/'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
