# Generated by Django 2.2.5 on 2019-10-31 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('Grupo', '0002_auto_20191030_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
