# Generated by Django 2.2.5 on 2019-10-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0003_auto_20191007_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipoTransaccion', models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Gasto')])),
                ('valor', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('icono', models.ImageField(blank=True, null=True, upload_to='transacciones/')),
                ('descripcion', models.TextField(max_length=500)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.CuentaGenerica')),
            ],
        ),
    ]
