# Generated by Django 2.2.5 on 2019-10-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionbase',
            name='tipoTransaccion',
            field=models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Gasto')], default=1),
        ),
    ]
