# Generated by Django 2.2.5 on 2019-10-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0002_auto_20191022_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionbase',
            name='tipoTransaccion',
            field=models.IntegerField(blank=True, choices=[(1, 'Ingreso'), (2, 'Gasto')], default=1, null=True),
        ),
    ]
