# Generated by Django 2.2.5 on 2019-11-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0003_auto_20191030_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionbase',
            name='tipo_moneda',
            field=models.PositiveIntegerField(choices=[(1, 'COP'), (2, 'USD'), (2, 'EUR'), (2, 'MXN')], default=1),
        ),
        migrations.AlterField(
            model_name='transaccionbase',
            name='tipoTransaccion',
            field=models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Gasto')], default=1),
        ),
    ]
