# Generated by Django 2.2.5 on 2019-11-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0004_auto_20191114_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionbase',
            name='tipo_moneda',
            field=models.CharField(choices=[('COP', 'COP'), ('USD', 'USD'), ('EUR', 'EUR'), ('MXN', 'MXN')], default='COP', max_length=3),
        ),
    ]
