# Generated by Django 2.2.5 on 2019-11-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_auto_20191115_1036'),
        ('transaccion', '0006_auto_20191114_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
                ('presupuestoDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='presupuesto.Presupuesto')),
                ('presupuestoOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='presupuesto.Presupuesto')),
            ],
        ),
    ]
