# Generated by Django 2.2.5 on 2019-12-05 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0008_transaccionpresupuesto_tipo_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosTransaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='transacciones/exportado')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccion.TransaccionBase')),
            ],
        ),
    ]
