# Generated by Django 2.2.5 on 2019-12-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0009_archivostransaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivostransaccion',
            name='archivo',
            field=models.FileField(upload_to='exportado'),
        ),
    ]
