# Generated by Django 2.2.5 on 2019-12-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0010_auto_20191204_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivosTransaccion',
        ),
    ]
